tap "caskroom/fonts"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "lsd"
brew "neovim", args: ["HEAD"]
brew "node"
brew "python"
brew "python@2"
brew "rbenv"
brew "ripgrep"
cask "alfred"
cask "dropbox"
cask "firefox"
cask "google-backup-and-sync"
cask "intellij-idea"
cask "iterm2"
cask "caskroom/fonts/font-sourcecodepro-nerd-font"
