defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain InitialKeyRepeat -int 15
defaults write com.apple.menuextra.battery ShowPercent -string YES
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock orientation -string left
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.dock magnification -bool yes
defaults write com.apple.dock tilesize -int 35
defaults write com.apple.finder ShowPathbar -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults write NSGlobalDomain _HIHideMenuBar -bool true
